
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ojeda
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
    int contJugada = 0;
    int contPiedra = 0;
    int contPapel = 0;
    int contTijeras = 0;
    int contLagarto = 0;
    int contSpock = 0;

    int contPer = 0;
    int contPC = 0;
    int empate = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("Elije tu tirada");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Suerte!");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/piedra.jpg"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/piedra2.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papel.jpg"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papel2.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tijeras.jpg"))); // NOI18N
        jButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tijeras2.JPG"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("Victorias PC");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setText("Victorias Usuario");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setText("Empates");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/spock.jpg"))); // NOI18N
        jButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/spock2.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lagarto.jpg"))); // NOI18N
        jButton5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lagarto2.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton6.setText("Cerrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(319, 319, 319)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton5)))
                    .addComponent(jButton4))
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Calculamos tiro de pc

        int pcJugada = IA();

        //Determinar el ganador
        if (pcJugada == 1) {
            jLabel1.setText("Usted tir\u00F3 Piedra, PC tir\u00F3 Piedra ");
            jLabel2.setText("Empate!");
            empate++;
            imprimirRes();
        }
        if (pcJugada == 2) {
            jLabel1.setText("Usted tir\u00F3 Piedra, PC tir\u00F3 Papel El papel envuelve la piedra");
            jLabel2.setText("PC gana!");
            contPC++;
            imprimirRes();
        }
        if (pcJugada == 3) {
            jLabel1.setText("Usted tir\u00F3 Piedra, PC tir\u00F3 Tijeras La piedra aplasta la tijera");
            jLabel2.setText("Usted gana!");
            contPer++;
            imprimirRes();
        }
        if (pcJugada == 4) {
            jLabel1.setText("Usted tir\u00F3 Piedra, PC tir\u00F3 Lagarto La piedra machaca al lagarto");
            jLabel2.setText("Usted gana!");
            contPer++;
            imprimirRes();
        }
        if (pcJugada == 5) {
            jLabel1.setText("Usted tir\u00F3 Piedra, PC tir\u00F3 Spock Spock vaporiza la piedra ");
            jLabel2.setText("PC gana!");
            contPC++;
            imprimirRes();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int pcJugada = IA();

        //Determinar el ganador
        if (pcJugada == 1) {
            jLabel1.setText("Usted tir\u00F3 Papel, PC tir\u00F3 Piedra El papel envuelve la piedra");
            jLabel2.setText("Usted gana!");
            contPer++;
            imprimirRes();
        }
        if (pcJugada == 2) {
            jLabel1.setText("Usted tir\u00F3 Papel, PC tir\u00F3 Papel");
            jLabel2.setText("Empate!");
            empate++;
            imprimirRes();
        }
        if (pcJugada == 3) {
            jLabel1.setText("Usted tir\u00F3 Papel, PC tir\u00F3 Tijeras La tijera corta el papel");
            jLabel2.setText("PC gana!");
            contPC++;
            imprimirRes();
        }
        if (pcJugada == 4) {
            jLabel1.setText("Usted tir\u00F3 Papel, PC tir\u00F3 Lagarto El lagarto se come el papel");
            jLabel2.setText("PC gana!");
            contPC++;
            imprimirRes();
        }
        if (pcJugada == 5) {
            jLabel1.setText("Usted tir\u00F3 Papel, PC tir\u00F3 Spock El papel desautoriza a Spock");
            jLabel2.setText("Usted gana!");
            contPer++;
            imprimirRes();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int pcJugada = IA();
        //Determinar el ganador
        if (pcJugada == 1) {
            jLabel1.setText("Usted tir\u00F3 Tijera, PC tir\u00F3 Piedra La piedra aplasta la tijera");
            jLabel2.setText("PC gana!");
            contPC++;
            imprimirRes();
        }
        if (pcJugada == 2) {
            jLabel1.setText("Usted tir\u00F3 Tijera, PC tir\u00F3 Papel La tijera corta el papel");
            jLabel2.setText("Usted gana!");
            contPer++;
            imprimirRes();
        }
        if (pcJugada == 3) {
            jLabel1.setText("Usted tir\u00F3 Tijera, PC tir\u00F3 Tijeras");
            jLabel2.setText("Empate!");
            empate++;
            imprimirRes();
        }
        if (pcJugada == 4) {
            jLabel1.setText("Usted tir\u00F3 Tijera, PC tir\u00F3 Lagarto La tijera decapita al lagarto");
            jLabel2.setText("Usted gana!");
            contPer++;
            imprimirRes();
        }
        if (pcJugada == 5) {
            jLabel1.setText("Usted tir\u00F3 Tijera, PC tir\u00F3 Spock Spock rompe las tijeras");
            jLabel2.setText("PC gana!");
            contPC++;
            imprimirRes();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Lagarto
        int pcJugada = IA();
        //Determinar el ganador
        if (pcJugada == 1) {
            jLabel1.setText("Usted tir\u00F3 Lagarto, PC tir\u00F3 Piedra La piedra machaca al lagarto");
            jLabel2.setText("PC gana!");
            contPC++;
            imprimirRes();
        }
        if (pcJugada == 2) {
            jLabel1.setText("Usted tir\u00F3 Lagarto, PC tir\u00F3 Papel El lagarto se come el papel");
            jLabel2.setText("Usted gana!");
            contPer++;
            imprimirRes();
        }
        if (pcJugada == 3) {
            jLabel1.setText("Usted tir\u00F3 Lagarto, PC tir\u00F3 Tijeras La tijera decapita al lagarto");
            jLabel2.setText("PC gana!");
            contPC++;
            imprimirRes();
        }
        if (pcJugada == 4) {
            jLabel1.setText("Usted tir\u00F3 Lagarto, PC tir\u00F3 Lagarto");
            jLabel2.setText("Empate!");
            empate++;
            imprimirRes();
        }
        if (pcJugada == 5) {
            jLabel1.setText("Usted tir\u00F3 Lagarto, PC tir\u00F3 Spock El lagarto envenena a Spock");
            jLabel2.setText("Usted gana!");
            contPer++;
            imprimirRes();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int pcJugada = IA();//Spock
        //Determinar el ganador
        if (pcJugada == 1) {
            jLabel1.setText("Usted tir\u00F3 Spock, PC tir\u00F3 Piedra Spock vaporiza la piedra");
            jLabel2.setText("Usted gana!");
            contPer++;
            imprimirRes();
        }
        if (pcJugada == 2) {
            jLabel1.setText("Usted tir\u00F3 Spock, PC tir\u00F3 Papel El papel desautoriza a Spock");
            jLabel2.setText("PC gana!");
            contPC++;
            imprimirRes();
        }
        if (pcJugada == 3) {
            jLabel1.setText("Usted tir\u00F3 Spock, PC tir\u00F3 Tijeras Spock rompe las tijeras");
            jLabel2.setText("Usted gana!");
            contPer++;
            imprimirRes();
        }
        if (pcJugada == 4) {
            jLabel1.setText("Usted tir\u00F3 Spock, PC tiro Lagart\u00F3 El lagarto envenena a Spock");
            jLabel2.setText("PC gana!");
            contPC++;
            imprimirRes();
        }
        if (pcJugada == 5) {
            jLabel1.setText("Usted tir\u00F3 Spock, PC tir\u00F3 Spock");
            jLabel2.setText("Empate!");
            empate++;
            imprimirRes();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    public int IA() {
        int res = 0;
        contJugada++;

        if (contJugada > 3) {
            res = tendencia();
            contadores(res);
        } else {
            res = (int) Math.floor(Math.random() * 5 + 1);
            System.out.println(contPiedra + "  " + contPapel + "  " + contTijeras + "  " + contLagarto + "  " + contSpock);
            switch (res) {
                case 1:
                    contPiedra++;
                    break;
                case 2:
                    contPapel++;
                    break;
                case 3:
                    contTijeras++;
                    break;
                case 4:
                    contLagarto++;
                    break;
                case 5:
                    contSpock++;
                    break;
                default:
                    break;
            }
        }
        //System.out.println(contJugada +" contJugada/respuestaPC" + res );
        return res;
    }

    public int tendencia() {
        System.out.println(contPiedra + "  " + contPapel + "  " + contTijeras + "  " + contLagarto + "  " + contSpock);

        int t = 0;
        int[] contadores = {contPiedra, contPapel, contTijeras, contLagarto, contSpock};
        int[] contadores2 = new int[5];
        int resIA = 0;

        // Ordenar los contadores de mayor a menor
        for (int i = 0; i < contadores.length - 1; i++) {
            int maxIndex = i;

            // Encontrar el índice del contador con el valor máximo
            for (int j = i + 1; j < contadores.length; j++) {
                if (contadores[j] > contadores[maxIndex]) {
                    maxIndex = j;
                }
            }

            // Intercambiar el contador actual con el contador de valor máximo
            int temp = contadores2[i];
            contadores2[i] = contadores2[maxIndex];
            contadores2[maxIndex] = temp;
        }

        if (contadores2[0] > contadores2[1] && contadores2[0] > contadores2[2] && contadores2[0] > contadores2[3] && contadores2[0] > contadores2[4]) {

            resIA = (int) Math.floor(Math.random() * 2 + 1);
            if (resIA == 1) {
                t = 2; // Papel
            } else {
                t = 5; // Spock
            }

        } else if (contadores2[1] > contadores2[0] && contadores2[1] > contadores2[2] && contadores2[1] > contadores2[3] && contadores2[1] > contadores2[4]) {

            resIA = (int) Math.floor(Math.random() * 2 + 1);
            if (resIA == 1) {
                t = 3; // Tijeras
            } else {
                t = 4; // Lagarto
            }

        } else if (contadores2[2] > contadores2[0] && contadores2[2] > contadores2[1] && contadores2[2] > contadores2[3] && contadores2[2] > contadores2[4]) {

            resIA = (int) Math.floor(Math.random() * 2 + 1);
            if (resIA == 1) {
                t = 1; // Piedra
            } else {
                t = 4; // Lagarto

            }
        } else if (contadores2[3] > contadores2[0] && contadores2[3] > contadores2[1] && contadores2[3] > contadores2[2] && contadores2[3] > contadores2[4]) {

            resIA = (int) Math.floor(Math.random() * 2 + 1);
            if (resIA == 1) {
                t = 2; // Tijeras
            } else {
                t = 3; // Piedra

            }
        } else if (contadores2[4] > contadores2[0] && contadores2[4] > contadores2[1] && contadores2[4] > contadores2[2] && contadores2[4] > contadores2[3]) {
            resIA = (int) Math.floor(Math.random() * 2 + 1);
            if (resIA == 1) {
                t = 2; // Papel
            } else {
                t = 4; // Lagarto

            }
        } else {// en caso de que al principio no se defina un mayor t se genera de manera aleatoria
            t = (int) Math.floor(Math.random() * 5 + 1);
        }

        return t;
    }

    public void contadores(int res) {
        switch (res) {
            case 1:
                contPiedra++;
                break;
            case 2:
                contPapel++;
                break;
            case 3:
                contTijeras++;
                break;
            case 4:
                contLagarto++;
                break;
            case 5:
                contSpock++;
                break;
            default:
                throw new AssertionError();
        }

    }

    public void imprimirRes() {
        jLabel3.setText("Victorias PC " + contPC);
        jLabel4.setText("Victorias Usuario " + contPer);
        jLabel5.setText("Empates " + empate);
    }
}
